// Shared email types for all VineTrack edge functions.
//
// Every application email (invitations, support, notifications, diagnostics)
// flows through this module. Supabase Auth email (recovery / signup /
// email-change) is generated by Auth itself and is NOT sent here.

/** Logical email categories recorded in email_delivery_events.email_type. */
export type EmailType =
  | "invitation"
  | "invitation_test"
  | "support_staff"
  | "support_receipt"
  | "notification"
  | "diagnostic";

/** Where the triggering request came from. */
export type SourcePlatform =
  | "ios"
  | "android"
  | "portal"
  | "portal_diagnostics"
  | "system"
  | "unknown";

/** Delivery lifecycle recorded in email_delivery_events.status. */
export type DeliveryStatus =
  | "submitted"
  | "sent"
  | "delivered"
  | "failed"
  | "bounced"
  | "complained"
  | "suppressed";

/** Stable machine-readable error codes returned to clients. */
export type EmailErrorCode =
  | "email_configuration_missing"
  | "provider_rejected"
  | "provider_unreachable"
  | "invalid_recipient";

export interface SendEmailRequest {
  from: string;
  to: string;
  replyTo?: string;
  subject: string;
  html: string;
  /** Optional Resend idempotency key to make retries safe. */
  idempotencyKey?: string;
}

export interface SendEmailResult {
  ok: boolean;
  providerId: string | null;
  errorCode: EmailErrorCode | null;
  /** Truncated, safe-to-log provider error detail. Never contains secrets. */
  errorDetail: string | null;
}

/** Context needed to write an email_delivery_events row. */
export interface DeliveryLogContext {
  emailType: EmailType;
  recipientEmail: string;
  sourcePlatform: SourcePlatform | string;
  actorUserId: string | null;
  /** Small structured context only — never tokens, links, or full HTML. */
  metadata: Record<string, unknown>;
}

/** Notification classes supported by the generic notification template. */
export type NotificationClass =
  | "information"
  | "reminder"
  | "warning"
  | "critical";
