// Supabase Edge Function: test-support-staff-email (System Admin diagnostics)
//
// Sends the REAL staff support-notification template (with a clear TEST
// banner and sample data) to the given recipient. NO support_requests row is
// created.
//
// Request (POST JSON):  { "recipient_email": "person@example.com" }
// Auth: authenticated caller + public.is_system_admin() must be true.
//
// Delivery event: email_type "support_staff" with metadata.test = true,
// source_platform "portal_diagnostics".

import { FROM_SUPPORT, REPLY_TO } from "../_shared/email/config.ts";
import {
  DIAGNOSTIC_CORS,
  prepareDiagnostic,
  sendDiagnosticEmail,
} from "../_shared/email/diagnostics.ts";
import {
  renderSupportStaffEmail,
  supportStaffSubject,
} from "../_shared/email/templates/support-staff.ts";

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: DIAGNOSTIC_CORS });
  }

  const prepared = await prepareDiagnostic(req);
  if ("response" in prepared) return prepared.response;

  return await sendDiagnosticEmail({
    context: prepared,
    emailType: "support_staff",
    templateName: "support_staff",
    functionName: "test-support-staff-email",
    from: FROM_SUPPORT,
    replyTo: REPLY_TO,
    subject: supportStaffSubject("diagnostics", "Sample support request", true),
    html: renderSupportStaffEmail({
      requestId: "00000000-0000-0000-0000-000000000000",
      category: "diagnostics",
      subject: "Sample support request",
      message:
        "This is a sample support message generated by the System Admin Email Diagnostics page. No real support request was created.",
      submitterName: prepared.adminName,
      submitterEmail: prepared.recipientEmail,
      vineyardName: "Example Vineyard",
      attachmentLinks: [],
      appPlatform: "diagnostics",
      appVersion: "—",
      appBuild: "—",
      deviceModel: "—",
      osVersion: "—",
      userId: prepared.actorUserId,
      isTest: true,
    }),
  });
});
