// Supabase Edge Function: test-notification-email (System Admin diagnostics)
//
// Sends the REAL generic notification template (with a clear TEST banner) to
// the given recipient. This is infrastructure verification only — nothing
// sends notification emails automatically yet.
//
// Request (POST JSON):
//   {
//     "recipient_email": "person@example.com",
//     "title"?: string,                 // structured fields only — clients
//     "summary"?: string,               // can never inject arbitrary HTML
//     "notification_type"?: "information" | "reminder" | "warning" | "critical",
//     "action_url"?: "https://…",       // https-only, otherwise omitted
//     "action_label"?: string
//   }
// Auth: authenticated caller + public.is_system_admin() must be true.
//
// Delivery event: email_type "notification" with metadata.test = true,
// source_platform "portal_diagnostics".

import { FROM_DEFAULT, REPLY_TO } from "../_shared/email/config.ts";
import {
  DIAGNOSTIC_CORS,
  prepareDiagnostic,
  sendDiagnosticEmail,
} from "../_shared/email/diagnostics.ts";
import {
  isNotificationClass,
  notificationSubject,
  renderNotificationEmail,
} from "../_shared/email/templates/notification-generic.ts";

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: DIAGNOSTIC_CORS });
  }

  const prepared = await prepareDiagnostic(req);
  if ("response" in prepared) return prepared.response;

  const body = prepared.body ?? {};
  const title = typeof body.title === "string" && body.title.trim()
    ? body.title.trim().slice(0, 120)
    : "Sample VineTrack notification";
  const summary = typeof body.summary === "string" && body.summary.trim()
    ? body.summary.trim().slice(0, 1000)
    : "This is a sample notification generated by the System Admin Email Diagnostics page. Future weather, disease-risk and task alerts will use this template.";
  const notificationType =
    typeof body.notification_type === "string" &&
      isNotificationClass(body.notification_type)
      ? body.notification_type
      : "information";
  const actionUrl = typeof body.action_url === "string"
    ? body.action_url.trim()
    : undefined;
  const actionLabel = typeof body.action_label === "string"
    ? body.action_label.trim().slice(0, 60)
    : undefined;

  return await sendDiagnosticEmail({
    context: prepared,
    emailType: "notification",
    templateName: "notification_generic",
    functionName: "test-notification-email",
    from: FROM_DEFAULT,
    replyTo: REPLY_TO,
    subject: notificationSubject({ title, notificationType, isTest: true }),
    html: renderNotificationEmail({
      title,
      summary,
      notificationType,
      actionUrl,
      actionLabel,
      isTest: true,
    }),
    extraMetadata: { notification_type: notificationType },
  });
});
