// Supabase Edge Function: test-support-receipt-email (System Admin diagnostics)
//
// Sends the REAL submitter-receipt template (with a clear TEST banner and
// sample data) to the given recipient. NO support_requests row is created.
//
// Request (POST JSON):  { "recipient_email": "person@example.com" }
// Auth: authenticated caller + public.is_system_admin() must be true.
//
// Delivery event: email_type "support_receipt" with metadata.test = true,
// source_platform "portal_diagnostics".

import { FROM_SUPPORT, REPLY_TO } from "../_shared/email/config.ts";
import {
  DIAGNOSTIC_CORS,
  prepareDiagnostic,
  sendDiagnosticEmail,
} from "../_shared/email/diagnostics.ts";
import {
  renderSupportReceiptEmail,
  supportReceiptSubject,
} from "../_shared/email/templates/support-receipt.ts";

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: DIAGNOSTIC_CORS });
  }

  const prepared = await prepareDiagnostic(req);
  if ("response" in prepared) return prepared.response;

  return await sendDiagnosticEmail({
    context: prepared,
    emailType: "support_receipt",
    templateName: "support_receipt",
    functionName: "test-support-receipt-email",
    from: FROM_SUPPORT,
    replyTo: REPLY_TO,
    subject: supportReceiptSubject(true),
    html: renderSupportReceiptEmail({
      requestId: "00000000-0000-0000-0000-000000000000",
      category: "diagnostics",
      subject: "Sample support request",
      summary:
        "This is a sample receipt generated by the System Admin Email Diagnostics page. No real support request was created.",
      submittedAt: new Date().toISOString(),
      submitterName: prepared.adminName,
      isTest: true,
    }),
  });
});
