package com.rork.vinetrack.data

import com.rork.vinetrack.data.model.parseIsoToEpochMs

/** Customer report dates only; pin timestamps and interchange identities are unchanged. */
class PinReportRegionalFormat(private val formatter: RegionFormatter) {
    fun dateTime(iso: String?): String? = parseIsoToEpochMs(iso)?.let { formatter.formatDateTime(it) }
    fun date(day: String): String = formatter.formatDate(day)
    fun generated(epochMs: Long): String = "Generated by VineTrack • ${formatter.formatDateTime(epochMs)}"
}
