package com.rork.vinetrack.data

import com.rork.vinetrack.data.insights.ScoutVisit
import com.rork.vinetrack.data.insights.ScoutWeatherSnapshot
import org.junit.Assert.*
import org.junit.Test

class RegionResidualBoundaryTest {
    private val au = RegionFormatter(RegionCountry.Australia.recommendedPreset.copy(timezone = "Australia/Sydney"))
    private val us = RegionFormatter(RegionCountry.UnitedStates.recommendedPreset.copy(timezone = "America/Los_Angeles", dateFormat = "MM/DD/YYYY"))

    @Test fun fuelCorrectionPreservesUntouchedCanonicalSeedAndSafetyBoundary() {
        for (fmt in listOf(au, us)) {
            val seed = RegionalInput.seed(12.1234567890123, fmt::fuelValue)
            assertEquals(seed.canonical, seed.resolve(seed.text, fmt::fuelToCanonical))
            assertEquals(25.0, seed.resolve(fmt.fuelValue(25.0).toString(), fmt::fuelToCanonical)!!, 1e-9)
            assertEquals(1000.0, seed.resolve(fmt.fuelValue(1000.0).toString(), fmt::fuelToCanonical)!!, 1e-9)
        }
        assertTrue(us.fuelToCanonical(1000.0) > 1000.0)
    }

    @Test fun blockIrrigationBoundaryPreservesSeedsAndInverseConverts() {
        for (fmt in listOf(au, us)) {
            val flow = RegionalInput.seed(2.1234567890123, fmt::volumeValue)
            val spacing = RegionalInput.seed(0.61234567890123, fmt::lengthValue)
            assertEquals(flow.canonical, flow.resolve(flow.text, fmt::volumeToCanonical))
            assertEquals(spacing.canonical, spacing.resolve(spacing.text, fmt::lengthToCanonical))
            assertEquals(4.0, flow.resolve(fmt.volumeValue(4.0).toString(), fmt::volumeToCanonical)!!, 1e-9)
            assertEquals(0.5, spacing.resolve(fmt.lengthValue(0.5).toString(), fmt::lengthToCanonical)!!, 1e-9)
        }
    }

    @Test fun damagedAreaConvertsHectaresToAcres() {
        assertEquals("2.10 ha", au.formatArea(2.1))
        assertEquals("5.19 ac", us.formatArea(2.1))
    }

    @Test fun scoutPdfWeatherUsesMetricImperialAndVineyardObservationTime() {
        val weather = ScoutWeatherSnapshot("2026-10-07T01:30:00Z", "2026-10-07T01:30:00Z", "station", 20.0, 60.0, 16.09344, null, null)
        val visit = ScoutVisit("visit", "vineyard", 2026, "2026-10-07", weather = weather, scoutUserId = null, scoutNameSnapshot = null, clientUpdatedAtIso = "2026-10-07T01:30:00Z")
        val metric = ScoutReportPdfExporter.weatherText(visit, au)
        val imperial = ScoutReportPdfExporter.weatherText(visit, us)
        assertTrue(metric.contains("20.0°C"))
        assertTrue(imperial.contains("68.0°F"))
        assertTrue(imperial.contains("10.0 mph"))
        assertTrue(imperial.contains("60%"))
        assertTrue(imperial.contains("10/06/2026 18:30"))
        assertEquals(20.0, weather.temperatureCelsius!!, 0.0)
    }

    @Test fun pinReportUsesVineyardDateAndTimezoneWithoutChangingTimestamp() {
        val iso = "2026-10-07T01:30:00Z"
        val auReport = PinReportRegionalFormat(au)
        val usReport = PinReportRegionalFormat(us)
        assertEquals("07/10/2026 12:30", auReport.dateTime(iso))
        assertEquals("10/06/2026 18:30", usReport.dateTime(iso))
        assertEquals("10/07/2026", usReport.date("2026-10-07"))
        assertEquals("Generated by VineTrack • 10/06/2026 18:30", usReport.generated(java.time.Instant.parse(iso).toEpochMilli()))
    }
}
