-- =============================================================================
-- 183: SUPERSEDED — DO NOT APPLY
--
-- This migration (single `variety_allocation_id` per picking record) was
-- WRITTEN BUT NEVER DEPLOYED to the live project. It is superseded by
-- sql/184_picking_record_planting_groups.sql, which implements the shared
-- PLANTING-GROUP identity contract instead:
--
--   * one pick links to a planting GROUP (Block + Variety + Clone +
--     Rootstock), which may span SEVERAL physical variety_allocations[]
--     sections — one arbitrary allocation id cannot represent that;
--   * member allocation ids are preserved under the group in
--     `variety_allocation_ids uuid[]`;
--   * the group identity is the deterministic `planting_group_key`.
--
-- Contract: docs/picking-records-allocation-identity-contract.md
-- sql/184 defensively drops the 183 artifacts in case this file was ever
-- applied anywhere. Do not apply this file; it is kept only as a numbered
-- tombstone so the migration sequence stays contiguous.
-- =============================================================================

select 1; -- intentional no-op
