-- =============================================================================
-- sql/199_apply_and_test.sql — ONE-PASTE runner for the Master Chemical
-- Catalogue (Stage 1). This generated file is exactly, in order:
--   1. A PREFLIGHT guard  — fails fast (changing nothing) if this is the wrong
--      Supabase project or prerequisites are missing.
--   2. sql/199_master_chemical_catalogue.sql — the migration (committed).
--   3. sql/tests/199_master_chemical_catalogue_tests.sql — verification tests
--      (rollback-only; they leave no data behind).
-- Do NOT edit this file — edit the two source files and regenerate by
-- re-concatenating them behind this header.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor (project tbafuqwruefgkbyxrxyb):
--   paste this ENTIRE file into one query tab and run it ONCE.
--   psql: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/199_apply_and_test.sql
--
-- EXPECTED OUTPUT (notices/messages panel)
--   PREFLIGHT OK ... T1..T12 "passed" notices ... and finally:
--   NOTICE: sql/199 master chemical catalogue tests: ALL PASSED
--
-- IF IT FAILS
--   * "PREFLIGHT FAILED ..."  -> wrong project or missing prerequisite;
--     nothing was changed. Check you are in tbafuqwruefgkbyxrxyb.
--   * A "Txx FAILED ..." error -> the migration itself is already applied
--     (it is additive and inert until a row is approved); copy the exact
--     error message back for investigation. Do not re-run the tests half.
--   * Re-running this whole file later is safe: the migration is idempotent
--     and the seed uses ON CONFLICT DO NOTHING.
-- =============================================================================

-- ---------------------------- PREFLIGHT -------------------------------------
do $$
begin
  if to_regclass('public.saved_chemicals') is null then
    raise exception using message =
      'PREFLIGHT FAILED: public.saved_chemicals does not exist in this database. '
      'This does not look like the VineTrack production project '
      '(tbafuqwruefgkbyxrxyb). Nothing was changed.';
  end if;
  if to_regprocedure('public.is_system_admin()') is null then
    raise exception using message =
      'PREFLIGHT FAILED: public.is_system_admin() is missing (it is created by '
      'sql/062_system_admin_and_feature_flags.sql). Apply that first. '
      'Nothing was changed.';
  end if;
  raise notice 'PREFLIGHT OK: applying sql/199 migration, then running its tests.';
end $$;

-- ============ 2. MIGRATION (sql/199_master_chemical_catalogue.sql) ==========

-- 199: Master Chemical Catalogue — Stage 1 (schema + server read foundation).
--
-- NUMBERING NOTE
--   The catalogue was drafted as "sql/197" in docs/master-chemical-catalogue-design.md
--   before sql/197 (spray block attribution security repair) and sql/198 (revision
--   concurrency) shipped. THIS migration is 199. Do not reuse 197/198.
--
-- WHAT THIS CREATES
--   * public.master_chemicals          — one row per country-scoped REGISTERED
--     product identity (e.g. AU:apvma:66541). A shared reference layer that
--     feeds lookups and re-verification. It is never the operator's record.
--   * public.master_chemical_versions — append-only history of every canonical
--     state a master row has ever had ("Saved Chemical was created from
--     revision 4; master is now revision 5").
--   * saved_chemicals.master_chemical_id / master_source_revision — OPTIONAL
--     provenance link from a vineyard's own record to the master product and
--     the revision its chemistry was copied at.
--   * A single seeded CANDIDATE row: the audited Custodia parity fixture.
--
-- TRUST MODEL (see docs/master-chemical-catalogue-design.md)
--   review_status: candidate -> approved -> retired.
--     candidate — enqueued from an AI lookup or drafted by an admin. NEVER
--                 served to app/portal lookup flows.
--     approved  — a human admin confirmed the row against the register/label.
--                 The ONLY state lookup flows may return as a master match.
--     retired   — registration lapsed/cancelled; kept for history.
--   `review_status` is the CATALOGUE lifecycle. It is deliberately a separate
--   column from `verification_status`, which is the sql/194 EVIDENCE state of
--   the chemistry data itself. Never conflate them.
--   A CHECK constraint makes ai_interpretation-sourced rows impossible to
--   approve: AI output alone can never become catalogue authority.
--
-- CHEMISTRY CONTRACT
--   The JSONB columns reuse the sql/194 wire shapes byte-for-byte
--   (docs/chemical-intelligence-json-contract.md §4): active_ingredients,
--   registered_uses, verification_sources, verification_conflicts. No second
--   chemistry format exists. As in sql/194, activity_groups has NO value CHECK
--   (the FRAC/HRAC/IRAC vocabulary grows annually).
--
-- VERSIONING
--   catalogue_version is a SERVER-MANAGED revision, independent of updated_at.
--   A BEFORE trigger bumps it exactly when canonical content changes and
--   ignores whatever version a client sends (no forgery, no accidental skips).
--   An AFTER trigger appends the full row image to master_chemical_versions.
--   Master corrections NEVER rewrite vineyard rows or spray snapshots; linked
--   vineyards see drift only through the Re-verify diff flow
--   (saved_chemicals.master_source_revision < master_chemicals.catalogue_version).
--
-- SEED STRATEGY (Stage 1 decision)
--   Exactly one row is seeded: Custodia 320 SC (AU:apvma:66541), the audited
--   cross-platform regression fixture (docs/chemical-custodia-parity-fixture.md).
--   It is seeded as a CANDIDATE, not approved, because the audit's own caveat
--   requires re-confirming registration currency in APVMA PubCRIS before any
--   approval — and candidates are invisible to every lookup flow, so shipping
--   this migration changes production lookup behaviour by exactly nothing
--   until an admin approves the row through Stage 2 review tooling.
--   Provenance is documented on the row itself (sources, review_notes).
--
-- SAFETY CONTRACT
--   * Purely ADDITIVE: no existing column dropped/renamed/retyped; the two new
--     saved_chemicals columns are nullable; old clients that never SELECT or
--     write them keep working unchanged (PostgREST PATCH/upsert payloads that
--     omit the columns leave them untouched).
--   * NO backfill of any kind. Existing saved_chemicals are NOT matched or
--     linked by name — linking happens only through the apps' identity-key
--     flows or explicit reviewed matching, never in bulk here.
--   * Historical spray snapshots (spray_records.tanks[].chemicalSnapshot) are
--     not read, not written, not referenced. They are a different artefact
--     with a different job and are never used as master history.
--   * Idempotent; single transaction.
--
-- RLS (sql/182 catalogue precedent)
--   * authenticated users read APPROVED rows only; system admins read all.
--   * writes (create/update/approve/retire) are system-admin only.
--   * version history is system-admin only (it can contain pre-publication
--     candidate states).
--   * The edge function's candidate enqueue uses the service role, which
--     bypasses RLS by design. No vineyard RLS is touched.

begin;

-- ---------------------------------------------------------------------------
-- 1. master_chemicals
-- ---------------------------------------------------------------------------

create table if not exists public.master_chemicals (
  id uuid primary key default gen_random_uuid(),

  -- Country-scoped registered identity — the ONLY identity that exists.
  -- Product name is never a uniqueness mechanism ("Custodia" vs "Custodia
  -- Forte"; AU "Custodia" vs UK "Custodia").
  registration_country text not null,
  registration_scheme  text not null,
  registration_number  text not null,
  registration_identity_key text generated always as (
    registration_country || ':' || registration_scheme || ':' || upper(btrim(registration_number))
  ) stored,
  registrant text,
  registered_product_name text not null,
  -- Lower-cased search aliases ONLY ("custodia"). Alias matching is exact
  -- whole-string equality — never substring — so "custodia" can never reach
  -- "Custodia Forte". Aliases never establish identity.
  common_names text[] not null default '{}',

  product_category text,
  form_type text,

  -- Chemistry: sql/194 wire shapes, byte-for-byte.
  active_ingredients jsonb not null default '[]'::jsonb,
  activity_groups text[] not null default '{}',
  activity_group_scheme text,
  registered_uses jsonb not null default '[]'::jsonb,
  label_rate_bases text[] not null default '{}',
  label_reference text,
  label_version text,

  -- sql/194 verification contract — the EVIDENCE state of the chemistry.
  -- Separate from review_status (the catalogue lifecycle) by design.
  verification_status text not null default 'unverified',
  verification_sources jsonb,
  verification_conflicts jsonb,
  verification_unresolved_fields text[],
  verified_at timestamptz,

  -- Provenance of the row itself.
  source_kind text not null default 'ai_interpretation',
  source_reference text,
  retrieved_at timestamptz,

  -- Catalogue lifecycle + review audit.
  review_status text not null default 'candidate',
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  review_notes text,

  -- Server-managed revision (see triggers) + contract versions.
  catalogue_version integer not null default 1,
  activity_group_table_version integer,
  intelligence_schema_version integer not null default 1,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint master_chemicals_identity_unique unique (registration_identity_key),
  constraint master_chemicals_country_check
    check (registration_country ~ '^[A-Z]{2}$'),
  constraint master_chemicals_number_check
    check (btrim(registration_number) <> ''),
  constraint master_chemicals_name_check
    check (btrim(registered_product_name) <> ''),
  constraint master_chemicals_registration_scheme_check
    check (registration_scheme in ('apvma','acvm','nz_epa','other')),
  constraint master_chemicals_activity_group_scheme_check
    check (activity_group_scheme is null or activity_group_scheme in
      ('frac','hrac','irac','not_applicable')),
  constraint master_chemicals_verification_status_check
    check (verification_status in
      ('verified','partially_verified','unverified','needs_match','conflict')),
  constraint master_chemicals_review_status_check
    check (review_status in ('candidate','approved','retired')),
  constraint master_chemicals_source_kind_check
    check (source_kind in ('official_register','manufacturer_label',
      'authoritative_classification','viticulture_reference',
      'ai_interpretation','manual_entry','legacy_record')),
  constraint master_chemicals_catalogue_version_check
    check (catalogue_version >= 1),
  -- THE approval gate: register/label provenance or it cannot be approved.
  constraint master_chemicals_approved_provenance_check
    check (review_status <> 'approved'
           or source_kind in ('official_register','manufacturer_label'))
);

comment on table public.master_chemicals is
  'Master Chemical Catalogue (sql/199). One row per country-scoped registered product '
  'identity (registration_identity_key, e.g. AU:apvma:66541). Only review_status=approved '
  'rows are served to lookup flows; candidates come from AI lookups or admin drafts and '
  'must be human-reviewed against the register/label before approval. catalogue_version '
  'is server-managed; history is append-only in master_chemical_versions.';
comment on column public.master_chemicals.review_status is
  'Catalogue lifecycle: candidate | approved | retired. NOT the same thing as '
  'verification_status (sql/194 evidence state of the chemistry data).';
comment on column public.master_chemicals.catalogue_version is
  'Server-managed revision. Bumped by trigger exactly when canonical content changes; '
  'client-supplied values are ignored. saved_chemicals.master_source_revision records '
  'which revision a vineyard record copied.';
comment on column public.master_chemicals.common_names is
  'Lower-cased exact-match search aliases only. Never identity, never fuzzy.';

-- ---------------------------------------------------------------------------
-- 2. master_chemical_versions — append-only history
-- ---------------------------------------------------------------------------

create table if not exists public.master_chemical_versions (
  id uuid primary key default gen_random_uuid(),
  master_chemical_id uuid not null references public.master_chemicals(id) on delete cascade,
  catalogue_version integer not null,
  -- Full row image at that version (to_jsonb of the row), so "what changed",
  -- "which label version", "when did registration data change" are all
  -- answerable later without guessing.
  snapshot jsonb not null,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now(),
  change_reason text,
  constraint master_chemical_versions_unique unique (master_chemical_id, catalogue_version)
);

comment on table public.master_chemical_versions is
  'Append-only canonical-state history for master_chemicals (sql/199). Trigger-written; '
  'never updated in place. NOT the same artefact as spray-line chemicalSnapshots, which '
  'freeze what was applied and are never consulted here.';

-- ---------------------------------------------------------------------------
-- 3. Server-managed revision + history triggers
-- ---------------------------------------------------------------------------

-- BEFORE trigger: owns id/created_at immutability, updated_at, and the
-- revision. The version a client sends is ALWAYS ignored — on insert it is 1,
-- on update it is OLD (no content change) or OLD+1 (content change).
create or replace function public.master_chemicals_before_write()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.catalogue_version := 1;
    new.created_at := now();
    new.updated_at := now();
    return new;
  end if;

  -- UPDATE
  new.id := old.id;
  new.created_at := old.created_at;
  new.updated_at := now();

  if (new.registration_country,          new.registration_scheme,
      new.registration_number,           new.registrant,
      new.registered_product_name,       new.product_category,
      new.form_type,                     new.active_ingredients,
      new.activity_groups,               new.activity_group_scheme,
      new.registered_uses,               new.label_rate_bases,
      new.label_reference,               new.label_version,
      new.verification_status,           new.verification_sources,
      new.verification_conflicts,        new.verification_unresolved_fields,
      new.verified_at,                   new.activity_group_table_version,
      new.intelligence_schema_version)
     is distinct from
     (old.registration_country,          old.registration_scheme,
      old.registration_number,           old.registrant,
      old.registered_product_name,       old.product_category,
      old.form_type,                     old.active_ingredients,
      old.activity_groups,               old.activity_group_scheme,
      old.registered_uses,               old.label_rate_bases,
      old.label_reference,               old.label_version,
      old.verification_status,           old.verification_sources,
      old.verification_conflicts,        old.verification_unresolved_fields,
      old.verified_at,                   old.activity_group_table_version,
      old.intelligence_schema_version)
  then
    new.catalogue_version := old.catalogue_version + 1;
  else
    -- Review/lifecycle/alias-only changes (approve, retire, notes,
    -- common_names) do not restate content, so they do not bump the revision
    -- linked vineyards compare against.
    new.catalogue_version := old.catalogue_version;
  end if;
  return new;
end$$;

-- AFTER trigger: appends the row image whenever a NEW revision exists.
-- SECURITY DEFINER (search_path pinned) so an authenticated admin's update can
-- write the RLS-protected history table — the sql/197/198 lesson: a guard that
-- silently fails to record is worse than no guard.
create or replace function public.master_chemicals_record_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.catalogue_version <> old.catalogue_version then
    insert into public.master_chemical_versions
      (master_chemical_id, catalogue_version, snapshot, changed_by, change_reason)
    values
      (new.id, new.catalogue_version, to_jsonb(new), auth.uid(),
       nullif(current_setting('vinetrack.master_change_reason', true), ''));
  end if;
  return new;
end$$;

drop trigger if exists t10_master_before_write on public.master_chemicals;
create trigger t10_master_before_write
before insert or update on public.master_chemicals
for each row execute function public.master_chemicals_before_write();

drop trigger if exists t20_master_record_version on public.master_chemicals;
create trigger t20_master_record_version
after insert or update on public.master_chemicals
for each row execute function public.master_chemicals_record_version();

-- ---------------------------------------------------------------------------
-- 4. saved_chemicals — additive provenance link
-- ---------------------------------------------------------------------------
-- No cascade and no SET NULL: a master row referenced by any vineyard record
-- cannot be hard-deleted (retire it instead), and a vineyard record never
-- loses its provenance silently.

alter table public.saved_chemicals
  add column if not exists master_chemical_id uuid references public.master_chemicals(id),
  add column if not exists master_source_revision integer;

do $$
begin
  alter table public.saved_chemicals
    add constraint saved_chemicals_master_source_revision_check
    check (master_source_revision is null or master_source_revision >= 1);
exception
  when duplicate_object then null;
end $$;

comment on column public.saved_chemicals.master_chemical_id is
  'Optional link to the master catalogue product this record was derived from (sql/199). '
  'Set only by identity-exact flows; NEVER backfilled by name similarity. Null is valid '
  'forever — an unlinked chemical keeps working exactly as before.';
comment on column public.saved_chemicals.master_source_revision is
  'master_chemicals.catalogue_version at the moment the structured chemistry was copied. '
  'master.catalogue_version > this  =>  "Updated verified information available" via the '
  'Re-verify diff flow. Master updates never rewrite the vineyard row.';

-- ---------------------------------------------------------------------------
-- 5. Indexes
-- ---------------------------------------------------------------------------

create index if not exists idx_master_chemicals_country_name
  on public.master_chemicals (registration_country, lower(registered_product_name));
create index if not exists idx_master_chemicals_common_names
  on public.master_chemicals using gin (common_names);
create index if not exists idx_master_chemicals_groups
  on public.master_chemicals using gin (activity_groups);
create index if not exists idx_master_chemicals_review
  on public.master_chemicals (review_status);
create index if not exists idx_saved_chemicals_master_chemical
  on public.saved_chemicals (master_chemical_id)
  where master_chemical_id is not null;

-- ---------------------------------------------------------------------------
-- 6. RLS
-- ---------------------------------------------------------------------------

alter table public.master_chemicals         enable row level security;
alter table public.master_chemical_versions enable row level security;

-- Reads: approved rows for everyone signed in; everything for system admins.
-- Candidates are structurally invisible to normal lookup paths (¶ candidate
-- isolation) — no client filter needed or trusted.
drop policy if exists master_chemicals_read on public.master_chemicals;
create policy master_chemicals_read
  on public.master_chemicals for select to authenticated
  using (review_status = 'approved' or public.is_system_admin());

-- Writes: system admins only. Vineyard users can never alter canonical
-- master data. (The edge function's candidate enqueue is service-role.)
drop policy if exists master_chemicals_admin_write on public.master_chemicals;
create policy master_chemicals_admin_write
  on public.master_chemicals for all to authenticated
  using (public.is_system_admin()) with check (public.is_system_admin());

drop policy if exists master_chemical_versions_read on public.master_chemical_versions;
create policy master_chemical_versions_read
  on public.master_chemical_versions for select to authenticated
  using (public.is_system_admin());

drop policy if exists master_chemical_versions_admin_write on public.master_chemical_versions;
create policy master_chemical_versions_admin_write
  on public.master_chemical_versions for all to authenticated
  using (public.is_system_admin()) with check (public.is_system_admin());

grant select, insert, update, delete on public.master_chemicals to authenticated;
grant select, insert, update, delete on public.master_chemical_versions to authenticated;
grant all on public.master_chemicals to service_role;
grant all on public.master_chemical_versions to service_role;

-- ---------------------------------------------------------------------------
-- 7. Seed — the audited Custodia parity fixture, as a CANDIDATE
-- ---------------------------------------------------------------------------
-- Values are the authoritative audit resolution of 2026-08-18
-- (docs/chemical-custodia-parity-fixture.md §1): AWRI registration update
-- (Sept 2012) + APVMA label mirror (agrobaseapp AU) + Adama Australia
-- literature. NOT taken from any earlier portal test value (the old synthetic
-- "62764" fixture is unrelated and must not reappear here).
--
-- Deliberately NOT approved: the fixture's own currency caveat requires
-- re-confirming the registration in APVMA PubCRIS before approval. An admin
-- approves it in Stage 2 review; until then no lookup can return it.

insert into public.master_chemicals (
  id,
  registration_country, registration_scheme, registration_number,
  registrant, registered_product_name, common_names,
  product_category, form_type,
  active_ingredients, activity_groups, activity_group_scheme,
  registered_uses, label_rate_bases,
  verification_status, verification_sources, verification_conflicts,
  verification_unresolved_fields, verified_at,
  source_kind, source_reference, retrieved_at,
  review_status, review_notes,
  activity_group_table_version, intelligence_schema_version
) values (
  'c0570d1a-2026-4a66-9541-a99f66541001',
  'AU', 'apvma', '66541',
  'Adama Australia Pty Ltd', 'Custodia 320 SC',
  array['custodia', 'custodia 320 sc'],
  'fungicide', 'liquid',
  '[
    {"name":"Azoxystrobin","concentration":120,"concentration_unit":"g/L",
     "activity_group":{"scheme":"frac","code":"11","common_name":"QoI / Strobilurin"},
     "group_source":"authoritative_classification","identity_source":"manufacturer_label"},
    {"name":"Tebuconazole","concentration":200,"concentration_unit":"g/L",
     "activity_group":{"scheme":"frac","code":"3","common_name":"DMI / Triazole"},
     "group_source":"authoritative_classification","identity_source":"manufacturer_label"}
  ]'::jsonb,
  array['3','11'], 'frac',
  '[
    {"crop":"Grapevines","target":"powdery_mildew","target_raw":"Powdery mildew",
     "rates":[
       {"label":"Dilute spraying","basis":"per_100_litres","value":65,"unit":"mL"},
       {"label":"Concentrate spraying","basis":"per_hectare","value":1,"unit":"L"}],
     "withholding_period_days":28,
     "restrictions":"Protectant only. DO NOT apply more than 2 sprays per season. Export grapes: do not use later than 80% capfall. Do not re-enter treated areas until the spray has dried."},
    {"crop":"Wheat","target_raw":"Stripe rust",
     "rates":[
       {"label":"Standard","basis":"range_per_hectare","min_value":315,"max_value":630,"unit":"mL"}],
     "withholding_period_days":42,
     "restrictions":"Harvest WHP 6 weeks. Grazing WHP 21 days."}
  ]'::jsonb,
  array['per_100_litres','per_hectare','range_per_hectare'],
  'partially_verified',
  '[
    {"kind":"manufacturer_label","name":"APVMA label — Custodia 320 SC (mirror via agrobaseapp AU)","reference":null,"retrieved_at":"2026-08-18T00:00:00Z"},
    {"kind":"viticulture_reference","name":"AWRI Agrochemicals registered for use in Australian viticulture — registration update (Sept 2012)","reference":null,"retrieved_at":"2026-08-18T00:00:00Z"},
    {"kind":"authoritative_classification","name":"VineTrack activity group reference v1 (FRAC/HRAC/IRAC)","reference":null,"retrieved_at":"2026-08-18T00:00:00Z"}
  ]'::jsonb,
  '[]'::jsonb,
  array['label_reference','label_version','re_entry_period_hours'],
  null,
  'manufacturer_label',
  'Audited cross-platform parity fixture (docs/chemical-custodia-parity-fixture.md). Sibling registrations that must NEVER merge with this identity: Custodia Forte AU:apvma:91636 (222/370 g/L); UK Custodia MAPP 16393 (GB:other:16393).',
  '2026-08-18T00:00:00Z',
  'candidate',
  'Seeded by sql/199 from the audited fixture. Approval WITHHELD by design: re-confirm registration currency in APVMA PubCRIS (Adama''s current AU grape offering is Custodia Forte; the original registration may lapse at a renewal cycle), then approve via Stage 2 admin review. Candidates are never served to lookups.',
  1, 1
)
on conflict on constraint master_chemicals_identity_unique do nothing;

commit;

-- ============ 3. TESTS (sql/tests/199_master_chemical_catalogue_tests.sql) ==========
-- Rollback-only: they commit nothing and leave no test data behind.

-- =============================================================================
-- Tests for sql/199_master_chemical_catalogue.sql
--
-- ROLLBACK-ONLY. Nothing is committed. Run with:
--   psql "$DATABASE_URL" -f sql/tests/199_master_chemical_catalogue_tests.sql
--
-- Write/read tests run as `authenticated` with RLS ACTIVE (the sql/195/197
-- lesson: owner-role tests cannot see RLS-dependent defects). Constraint-level
-- tests run as postgres because constraints must hold even for admins.
--
-- Coverage
--   T1  migration in place (tables, identity column, triggers, RLS, policies,
--       saved_chemicals link columns, Custodia seed present as CANDIDATE)
--   T2  registration identity uniqueness (dup, whitespace dup, case rules,
--       Forte 91636 distinct, AU vs GB same-number distinct)
--   T3  lifecycle vocabulary + THE approval gate (ai_interpretation rows can
--       never be approved; manufacturer_label rows can)
--   T4  server-managed revision: content bumps, review-only edits do not,
--       client-supplied versions are ignored (no forgery), history appends
--   T5  RLS reads: normal user sees approved only (candidate + retired
--       invisible); admin sees everything
--   T6  RLS writes: normal user cannot insert/update/delete master rows;
--       admin can, and admin updates write history (SECURITY DEFINER path)
--   T7  version history is admin-only, and not writable by normal users
--   T8  saved_chemicals link: valid link OK, bogus FK rejected, unlinked
--       (old-client shape) rows stay valid
--   T9  master revision moves on -> saved chemical NOT rewritten, drift
--       detectable (master_source_revision < catalogue_version)
--   T10 vineyard-only edits (price/stock) touch neither master nor link
--   T11 historical spray snapshot immune to master + saved-chemical updates
--   T12 cross-vineyard isolation + a referenced master row cannot be deleted
--   T13 rollback
--
-- Expected final line:
--   NOTICE: sql/199 master chemical catalogue tests: ALL PASSED
-- =============================================================================
begin;

-- ---------------- T1 preconditions ----------------
do $$
declare
  v_seed record;
begin
  if to_regclass('public.master_chemicals') is null then
    raise exception 'T1 FAILED: master_chemicals missing (sql/199 not applied)';
  end if;
  if to_regclass('public.master_chemical_versions') is null then
    raise exception 'T1 FAILED: master_chemical_versions missing';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_schema='public' and table_name='master_chemicals'
                    and column_name='registration_identity_key' and is_generated='ALWAYS') then
    raise exception 'T1 FAILED: registration_identity_key must be a generated column';
  end if;
  if not exists (select 1 from pg_constraint
                  where conname='master_chemicals_identity_unique') then
    raise exception 'T1 FAILED: identity unique constraint missing';
  end if;
  if not exists (select 1 from pg_constraint
                  where conname='master_chemicals_approved_provenance_check') then
    raise exception 'T1 FAILED: approved-provenance CHECK missing';
  end if;
  if (select count(*) from pg_trigger g join pg_class c on c.oid=g.tgrelid
       where c.relname='master_chemicals' and not g.tgisinternal
         and g.tgname in ('t10_master_before_write','t20_master_record_version')) <> 2 then
    raise exception 'T1 FAILED: revision/history triggers not attached';
  end if;
  if not (select relrowsecurity from pg_class where relname='master_chemicals') then
    raise exception 'T1 FAILED: RLS not enabled on master_chemicals';
  end if;
  if not (select relrowsecurity from pg_class where relname='master_chemical_versions') then
    raise exception 'T1 FAILED: RLS not enabled on master_chemical_versions';
  end if;
  if (select count(*) from pg_policies
       where schemaname='public' and tablename='master_chemicals') < 2 then
    raise exception 'T1 FAILED: master_chemicals policies missing';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_schema='public' and table_name='saved_chemicals'
                    and column_name='master_chemical_id') then
    raise exception 'T1 FAILED: saved_chemicals.master_chemical_id missing';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_schema='public' and table_name='saved_chemicals'
                    and column_name='master_source_revision') then
    raise exception 'T1 FAILED: saved_chemicals.master_source_revision missing';
  end if;

  -- The audited Custodia fixture must be seeded, as a CANDIDATE, at version 1,
  -- with its version-1 history row already recorded by the trigger.
  select * into v_seed from public.master_chemicals
   where registration_identity_key = 'AU:apvma:66541';
  if v_seed.id is null then
    raise exception 'T1 FAILED: Custodia seed (AU:apvma:66541) missing';
  end if;
  if v_seed.review_status <> 'candidate' then
    raise exception 'T1 FAILED: Custodia seed must be a candidate (PubCRIS currency unconfirmed), got %', v_seed.review_status;
  end if;
  if v_seed.catalogue_version <> 1 then
    raise exception 'T1 FAILED: seed catalogue_version expected 1, got %', v_seed.catalogue_version;
  end if;
  if v_seed.registered_product_name <> 'Custodia 320 SC'
     or v_seed.registrant <> 'Adama Australia Pty Ltd' then
    raise exception 'T1 FAILED: seed identity naming wrong';
  end if;
  if jsonb_array_length(v_seed.active_ingredients) <> 2 then
    raise exception 'T1 FAILED: seed must carry exactly two actives';
  end if;
  if v_seed.activity_groups <> array['3','11'] then
    raise exception 'T1 FAILED: seed activity_groups expected {3,11}, got %', v_seed.activity_groups;
  end if;
  if v_seed.verification_status <> 'partially_verified' then
    raise exception 'T1 FAILED: seed verification_status expected partially_verified';
  end if;
  if not ('re_entry_period_hours' = any(v_seed.verification_unresolved_fields)) then
    raise exception 'T1 FAILED: seed must keep re_entry_period_hours unresolved (never invented)';
  end if;
  if not exists (select 1 from public.master_chemical_versions
                  where master_chemical_id = v_seed.id and catalogue_version = 1) then
    raise exception 'T1 FAILED: seed version-1 history row missing';
  end if;

  raise notice 'T1 passed (sql/199 in place; Custodia seeded as candidate with v1 history)';
end$$;

-- ---------------- fixtures ----------------
do $$
declare
  u_a uuid; u_b uuid; u_adm uuid;
  v_master uuid;
begin
  perform set_config('role', 'postgres', true);

  insert into auth.users (id, instance_id, aud, role, email, encrypted_password,
                          email_confirmed_at, created_at, updated_at)
  values
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'authenticated',
     'authenticated', 't199-member@test.local', 'x', now(), now(), now()),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'authenticated',
     'authenticated', 't199-outsider@test.local', 'x', now(), now(), now()),
    (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'authenticated',
     'authenticated', 't199-admin@test.local', 'x', now(), now(), now());

  select id into u_a   from auth.users where email = 't199-member@test.local';
  select id into u_b   from auth.users where email = 't199-outsider@test.local';
  select id into u_adm from auth.users where email = 't199-admin@test.local';

  insert into public.profiles (id, email) values
    (u_a, 't199-member@test.local'), (u_b, 't199-outsider@test.local'),
    (u_adm, 't199-admin@test.local')
  on conflict (id) do nothing;

  insert into public.vineyards (id, name) values
    ('d9990000-0000-0000-0000-000000000001', 'T199 Home');

  insert into public.vineyard_members (vineyard_id, user_id, role) values
    ('d9990000-0000-0000-0000-000000000001', u_a, 'manager');

  insert into public.system_admins (user_id, email, is_active)
  values (u_adm, 't199-admin@test.local', true);

  -- One APPROVED master fixture, created with register/label provenance, that
  -- the RLS + linking tests read. (Rolled back with everything else.)
  insert into public.master_chemicals (
    registration_country, registration_scheme, registration_number,
    registrant, registered_product_name, common_names,
    product_category, form_type,
    active_ingredients, activity_groups, activity_group_scheme,
    registered_uses, label_rate_bases,
    verification_status, verification_sources, verification_unresolved_fields,
    verified_at, source_kind, retrieved_at, review_status, reviewed_by, reviewed_at
  ) values (
    'AU', 'apvma', '90001',
    'T199 Registrant Pty Ltd', 'T199 Shield 500 SC', array['t199 shield'],
    'fungicide', 'liquid',
    '[{"name":"Azoxystrobin","concentration":500,"concentration_unit":"g/L",
       "activity_group":{"scheme":"frac","code":"11","common_name":"QoI / Strobilurin"},
       "group_source":"authoritative_classification","identity_source":"manufacturer_label"}]'::jsonb,
    array['11'], 'frac',
    '[{"crop":"Grapevines","target":"powdery_mildew","target_raw":"Powdery mildew",
       "rates":[{"label":"Standard","basis":"per_hectare","value":0.5,"unit":"L"}],
       "withholding_period_days":14,"restrictions":null}]'::jsonb,
    array['per_hectare'],
    'verified',
    '[{"kind":"manufacturer_label","name":"T199 label","reference":null,"retrieved_at":"2026-08-18T00:00:00Z"}]'::jsonb,
    '{}',
    '2026-08-18T00:00:00Z', 'manufacturer_label', '2026-08-18T00:00:00Z',
    'approved', u_adm, now()
  ) returning id into v_master;

  perform set_config('vinetrack.t199_user_a',   u_a::text,     false);
  perform set_config('vinetrack.t199_user_b',   u_b::text,     false);
  perform set_config('vinetrack.t199_user_adm', u_adm::text,   false);
  perform set_config('vinetrack.t199_master',   v_master::text, false);
end$$;

-- Helper: become one of the fixture users, with RLS enforced.
create or replace function public._t199_login(p_which text)
returns void language plpgsql as $$
declare v_uid text;
begin
  v_uid := current_setting('vinetrack.t199_user_' || p_which, true);
  perform set_config('role', 'postgres', true);
  perform set_config('request.jwt.claims',
    json_build_object('sub', v_uid, 'role', 'authenticated')::text, true);
  perform set_config('role', 'authenticated', true);
end$$;

-- =====================================================================
-- T2  REGISTRATION IDENTITY UNIQUENESS
-- =====================================================================
do $$
declare
  v_caught boolean;
begin
  perform set_config('role', 'postgres', true);

  -- Exact duplicate of the seeded Custodia identity.
  v_caught := false;
  begin
    insert into public.master_chemicals
      (registration_country, registration_scheme, registration_number, registered_product_name)
    values ('AU', 'apvma', '66541', 'Custodia clone');
  exception when unique_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T2 FAILED: duplicate AU:apvma:66541 was accepted — two approved-track rows for one registration';
  end if;

  -- Whitespace / case games on the number must hit the SAME identity.
  v_caught := false;
  begin
    insert into public.master_chemicals
      (registration_country, registration_scheme, registration_number, registered_product_name)
    values ('AU', 'apvma', '  66541  ', 'Custodia padded clone');
  exception when unique_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T2 FAILED: padded registration number bypassed identity uniqueness';
  end if;

  -- Country must be canonical ISO-2 uppercase — no 'au' side-channel identity.
  v_caught := false;
  begin
    insert into public.master_chemicals
      (registration_country, registration_scheme, registration_number, registered_product_name)
    values ('au', 'apvma', '66541', 'Custodia lowercase country');
  exception when check_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T2 FAILED: lowercase country accepted (identity canonicalisation hole)';
  end if;

  -- Custodia FORTE is a different registration — must insert cleanly.
  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number,
     registrant, registered_product_name, common_names)
  values ('AU', 'apvma', '91636', 'Adama Australia Pty Ltd', 'Custodia Forte',
          array['custodia forte']);

  -- The same NUMBER in another country is a different product identity.
  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number, registered_product_name)
  values ('GB', 'other', '16393', 'Custodia (UK)');
  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number, registered_product_name)
  values ('AU', 'other', '16393', 'T199 same-number different-country');

  raise notice 'T2 passed (identity unique; Forte + cross-country identities distinct)';
end$$;

-- =====================================================================
-- T3  LIFECYCLE VOCABULARY + APPROVAL PROVENANCE GATE
-- =====================================================================
do $$
declare
  v_caught boolean;
  v_ai uuid;
begin
  perform set_config('role', 'postgres', true);

  v_caught := false;
  begin
    insert into public.master_chemicals
      (registration_country, registration_scheme, registration_number,
       registered_product_name, review_status)
    values ('AU', 'apvma', '90002', 'T199 bogus status', 'published');
  exception when check_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T3 FAILED: unknown review_status accepted';
  end if;

  -- An AI-sourced candidate exists...
  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number,
     registered_product_name, source_kind, review_status)
  values ('AU', 'apvma', '90003', 'T199 AI candidate', 'ai_interpretation', 'candidate')
  returning id into v_ai;

  -- ...and can NEVER be approved while its only provenance is the AI.
  v_caught := false;
  begin
    update public.master_chemicals set review_status = 'approved' where id = v_ai;
  exception when check_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T3 FAILED: ai_interpretation row was approved — AI output laundered into authority';
  end if;

  -- With register/label provenance recorded, approval is possible.
  update public.master_chemicals
     set source_kind = 'manufacturer_label', review_status = 'approved'
   where id = v_ai;
  if (select review_status from public.master_chemicals where id = v_ai) <> 'approved' then
    raise exception 'T3 FAILED: label-backed approval did not stick';
  end if;

  -- Retire works and is terminal-but-kept.
  update public.master_chemicals set review_status = 'retired' where id = v_ai;
  if not exists (select 1 from public.master_chemicals where id = v_ai and review_status='retired') then
    raise exception 'T3 FAILED: retirement lost the row';
  end if;

  raise notice 'T3 passed (lifecycle vocabulary enforced; AI can never be approved)';
end$$;

-- =====================================================================
-- T4  SERVER-MANAGED REVISION + APPEND-ONLY HISTORY
-- =====================================================================
do $$
declare
  v_id uuid;
  v_ver integer;
  v_hist integer;
begin
  perform set_config('role', 'postgres', true);

  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number,
     registrant, registered_product_name, source_kind)
  values ('NZ', 'acvm', 'T199-REV', 'Original Registrant', 'T199 Revision Probe',
          'manufacturer_label')
  returning id into v_id;

  select catalogue_version into v_ver from public.master_chemicals where id = v_id;
  if v_ver <> 1 then
    raise exception 'T4 FAILED: new row should start at catalogue_version 1, got %', v_ver;
  end if;
  select count(*) into v_hist from public.master_chemical_versions where master_chemical_id = v_id;
  if v_hist <> 1 then
    raise exception 'T4 FAILED: insert should record history v1 (got % rows)', v_hist;
  end if;

  -- Canonical content change -> bump + history.
  update public.master_chemicals set registrant = 'Corrected Registrant' where id = v_id;
  select catalogue_version into v_ver from public.master_chemicals where id = v_id;
  if v_ver <> 2 then
    raise exception 'T4 FAILED: content change should bump to 2, got %', v_ver;
  end if;
  if not exists (select 1 from public.master_chemical_versions
                  where master_chemical_id = v_id and catalogue_version = 2
                    and snapshot->>'registrant' = 'Corrected Registrant') then
    raise exception 'T4 FAILED: v2 history snapshot missing or wrong';
  end if;
  if not exists (select 1 from public.master_chemical_versions
                  where master_chemical_id = v_id and catalogue_version = 1
                    and snapshot->>'registrant' = 'Original Registrant') then
    raise exception 'T4 FAILED: v1 history was rewritten — history must be append-only';
  end if;

  -- Review-only change -> NO bump, NO history.
  update public.master_chemicals set review_notes = 'checked' where id = v_id;
  select catalogue_version into v_ver from public.master_chemicals where id = v_id;
  if v_ver <> 2 then
    raise exception 'T4 FAILED: review-notes edit bumped the revision (got %)', v_ver;
  end if;

  -- Forged client version WITHOUT content change is ignored.
  update public.master_chemicals set catalogue_version = 99 where id = v_id;
  select catalogue_version into v_ver from public.master_chemicals where id = v_id;
  if v_ver <> 2 then
    raise exception 'T4 FAILED: client forged catalogue_version to % without content change', v_ver;
  end if;

  -- Forged client version WITH content change still lands on old+1.
  update public.master_chemicals
     set catalogue_version = 99, label_version = 'Rev B 2026'
   where id = v_id;
  select catalogue_version into v_ver from public.master_chemicals where id = v_id;
  if v_ver <> 3 then
    raise exception 'T4 FAILED: content change with forged version should land on 3, got %', v_ver;
  end if;
  select count(*) into v_hist from public.master_chemical_versions where master_chemical_id = v_id;
  if v_hist <> 3 then
    raise exception 'T4 FAILED: expected 3 history rows, got %', v_hist;
  end if;

  raise notice 'T4 passed (server-managed revision; forgery ignored; append-only history)';
end$$;

-- =====================================================================
-- T5  RLS READS — approved only for normal users; admin sees all
-- =====================================================================
do $$
declare
  v_n integer;
begin
  -- A retired row exists (from T3) and the Custodia candidate is seeded.
  perform public._t199_login('a');

  select count(*) into v_n from public.master_chemicals
   where registration_identity_key = 'AU:apvma:90001';
  if v_n <> 1 then
    raise exception 'T5 FAILED: member cannot read an APPROVED master product';
  end if;

  select count(*) into v_n from public.master_chemicals
   where registration_identity_key = 'AU:apvma:66541';
  if v_n <> 0 then
    raise exception 'T5 FAILED: CANDIDATE (Custodia seed) is visible to a normal user — candidate isolation broken';
  end if;

  select count(*) into v_n from public.master_chemicals
   where registration_identity_key = 'AU:apvma:90003';
  if v_n <> 0 then
    raise exception 'T5 FAILED: RETIRED row visible to a normal user';
  end if;

  perform public._t199_login('adm');
  select count(*) into v_n from public.master_chemicals
   where registration_identity_key in ('AU:apvma:66541','AU:apvma:90001','AU:apvma:90003');
  if v_n <> 3 then
    raise exception 'T5 FAILED: admin should see candidate + approved + retired (saw %)', v_n;
  end if;

  raise notice 'T5 passed (approved-only reads; candidates/retired invisible; admin sees all)';
end$$;

-- =====================================================================
-- T6  RLS WRITES — normal users never alter the catalogue; admins do,
--     and admin updates record history through RLS (SECURITY DEFINER)
-- =====================================================================
do $$
declare
  v_caught boolean;
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_ver integer;
  v_hist integer;
begin
  perform public._t199_login('a');

  v_caught := false;
  begin
    insert into public.master_chemicals
      (registration_country, registration_scheme, registration_number, registered_product_name)
    values ('AU', 'apvma', '90050', 'T199 member insert');
  exception when insufficient_privilege then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T6 FAILED: a normal vineyard user inserted a master row';
  end if;

  update public.master_chemicals set registrant = 'HACKED' where id = v_master;
  perform public._t199_login('adm');
  if exists (select 1 from public.master_chemicals where id = v_master and registrant = 'HACKED') then
    raise exception 'T6 FAILED: a normal vineyard user modified a master row';
  end if;

  perform public._t199_login('a');
  delete from public.master_chemicals where id = v_master;
  perform public._t199_login('adm');
  if not exists (select 1 from public.master_chemicals where id = v_master) then
    raise exception 'T6 FAILED: a normal vineyard user deleted a master row';
  end if;

  -- Admin content update under RLS: bumps revision AND records history
  -- (the SECURITY DEFINER trigger path real admin sessions will use).
  select catalogue_version into v_ver from public.master_chemicals where id = v_master;
  update public.master_chemicals
     set label_version = 'T199 admin correction'
   where id = v_master;
  if (select catalogue_version from public.master_chemicals where id = v_master) <> v_ver + 1 then
    raise exception 'T6 FAILED: admin content update did not bump the revision';
  end if;
  select count(*) into v_hist from public.master_chemical_versions
   where master_chemical_id = v_master and catalogue_version = v_ver + 1;
  if v_hist <> 1 then
    raise exception 'T6 FAILED: admin update did not record history under RLS';
  end if;

  insert into public.master_chemicals
    (registration_country, registration_scheme, registration_number,
     registered_product_name, source_kind, review_status)
  values ('AU', 'apvma', '90051', 'T199 admin draft', 'manual_entry', 'candidate');

  raise notice 'T6 passed (catalogue writes are admin-only; admin history recorded under RLS)';
end$$;

-- =====================================================================
-- T7  VERSION HISTORY IS ADMIN-ONLY
-- =====================================================================
do $$
declare
  v_n integer;
  v_caught boolean;
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
begin
  perform public._t199_login('a');
  select count(*) into v_n from public.master_chemical_versions;
  if v_n <> 0 then
    raise exception 'T7 FAILED: normal user can read master version history (% rows)', v_n;
  end if;

  v_caught := false;
  begin
    insert into public.master_chemical_versions (master_chemical_id, catalogue_version, snapshot)
    values (v_master, 999, '{}'::jsonb);
  exception when insufficient_privilege then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T7 FAILED: normal user wrote master version history';
  end if;

  perform public._t199_login('adm');
  select count(*) into v_n from public.master_chemical_versions where master_chemical_id = v_master;
  if v_n < 2 then
    raise exception 'T7 FAILED: admin should see the master''s history rows';
  end if;

  raise notice 'T7 passed (version history admin-only)';
end$$;

-- =====================================================================
-- T8  SAVED CHEMICAL LINK — valid link, FK integrity, old clients
-- =====================================================================
do $$
declare
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_caught boolean;
  v_rev integer;
begin
  perform public._t199_login('a');

  -- Link a vineyard record to the approved master at its current revision,
  -- exactly as "create Saved Chemical from Master" will.
  insert into public.saved_chemicals
    (id, vineyard_id, name, active_ingredient, chemical_group,
     registration_country, registration_scheme, registration_number,
     master_chemical_id, master_source_revision, client_updated_at)
  select 'd9990000-0000-0000-0000-00000000c001', 'd9990000-0000-0000-0000-000000000001',
         'T199 Shield 500 SC', 'Azoxystrobin 500 g/L', '11',
         'AU', 'apvma', '90001',
         mc.id, mc.catalogue_version, now()
    from public.master_chemicals mc where mc.id = v_master;

  select master_source_revision into v_rev from public.saved_chemicals
   where id = 'd9990000-0000-0000-0000-00000000c001';
  if v_rev is null then
    raise exception 'T8 FAILED: master_source_revision was not stored';
  end if;

  -- A link must point at a real master row.
  v_caught := false;
  begin
    insert into public.saved_chemicals
      (id, vineyard_id, name, master_chemical_id, master_source_revision, client_updated_at)
    values ('d9990000-0000-0000-0000-00000000c002', 'd9990000-0000-0000-0000-000000000001',
            'T199 dangling link', gen_random_uuid(), 1, now());
  exception when foreign_key_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T8 FAILED: saved chemical accepted a dangling master link';
  end if;

  -- Old-client shape: no master columns at all. Must stay perfectly valid.
  insert into public.saved_chemicals (id, vineyard_id, name, client_updated_at)
  values ('d9990000-0000-0000-0000-00000000c003', 'd9990000-0000-0000-0000-000000000001',
          'T199 legacy unlinked', now());
  if (select master_chemical_id from public.saved_chemicals
       where id = 'd9990000-0000-0000-0000-00000000c003') is not null then
    raise exception 'T8 FAILED: unlinked row grew a master link from nowhere';
  end if;

  raise notice 'T8 passed (link stored with revision; FK enforced; old clients unaffected)';
end$$;

-- =====================================================================
-- T9  MASTER MOVES ON -> SAVED CHEMICAL UNCHANGED, DRIFT DETECTABLE
-- =====================================================================
do $$
declare
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_master_ver integer;
  v_saved record;
begin
  -- Admin corrects the master product (a label correction).
  perform public._t199_login('adm');
  update public.master_chemicals
     set active_ingredients = jsonb_set(active_ingredients, '{0,concentration}', '480'::jsonb)
   where id = v_master;
  select catalogue_version into v_master_ver from public.master_chemicals where id = v_master;

  -- The vineyard's record is EXACTLY as it was — no silent rewrite.
  perform public._t199_login('a');
  select * into v_saved from public.saved_chemicals
   where id = 'd9990000-0000-0000-0000-00000000c001';
  if v_saved.active_ingredient <> 'Azoxystrobin 500 g/L' then
    raise exception 'T9 FAILED: master correction rewrote a vineyard record';
  end if;
  if v_saved.master_source_revision >= v_master_ver then
    raise exception 'T9 FAILED: drift not detectable (saved rev % vs master rev %)',
      v_saved.master_source_revision, v_master_ver;
  end if;

  -- The exact query Re-verify will run: "is updated verified info available?"
  if not exists (
    select 1 from public.saved_chemicals sc
      join public.master_chemicals mc on mc.id = sc.master_chemical_id
     where sc.id = 'd9990000-0000-0000-0000-00000000c001'
       and mc.catalogue_version > sc.master_source_revision
  ) then
    raise exception 'T9 FAILED: member cannot detect that updated master information exists';
  end if;

  raise notice 'T9 passed (master rev % > saved rev %; vineyard record untouched)',
    v_master_ver, v_saved.master_source_revision;
end$$;

-- =====================================================================
-- T10  VINEYARD-ONLY EDITS TOUCH NEITHER MASTER NOR LINK
-- =====================================================================
do $$
declare
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_ver_before integer;
  v_hist_before integer;
  v_saved record;
begin
  perform public._t199_login('adm');
  select catalogue_version into v_ver_before from public.master_chemicals where id = v_master;
  select count(*) into v_hist_before from public.master_chemical_versions
   where master_chemical_id = v_master;

  -- The operator edits price/stock — vineyard-private commercial data.
  perform public._t199_login('a');
  update public.saved_chemicals
     set price_per_pack = 189.50, inventory_quantity = 4,
         notes = 'shed 2', client_updated_at = now()
   where id = 'd9990000-0000-0000-0000-00000000c001';

  select * into v_saved from public.saved_chemicals
   where id = 'd9990000-0000-0000-0000-00000000c001';
  if v_saved.master_chemical_id is distinct from v_master then
    raise exception 'T10 FAILED: a price edit disturbed the master link';
  end if;

  perform public._t199_login('adm');
  if (select catalogue_version from public.master_chemicals where id = v_master) <> v_ver_before then
    raise exception 'T10 FAILED: a vineyard edit changed the MASTER product';
  end if;
  if (select count(*) from public.master_chemical_versions where master_chemical_id = v_master)
     <> v_hist_before then
    raise exception 'T10 FAILED: a vineyard edit wrote master history';
  end if;

  raise notice 'T10 passed (vineyard commercial edits never touch the master)';
end$$;

-- =====================================================================
-- T11  HISTORICAL SPRAY SNAPSHOT IS IMMUNE
-- =====================================================================
do $$
declare
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_tanks_before text;
  v_tanks_after text;
begin
  perform public._t199_login('a');

  insert into public.spray_records (id, vineyard_id, date, tanks, client_updated_at)
  values ('d9990000-0000-0000-0000-00000000e001', 'd9990000-0000-0000-0000-000000000001',
          now(),
          '[{"chemicals":[{"name":"T199 Shield 500 SC",
             "chemicalSnapshot":{"activity_groups":["11"],
               "registration_identity_key":"AU:apvma:90001",
               "verification_status":"verified","schema_version":1}}]}]'::jsonb,
          now());

  select tanks::text into v_tanks_before from public.spray_records
   where id = 'd9990000-0000-0000-0000-00000000e001';

  -- Master corrected AND the saved chemical re-labelled afterwards…
  perform public._t199_login('adm');
  update public.master_chemicals
     set registered_uses = jsonb_set(registered_uses, '{0,withholding_period_days}', '21'::jsonb)
   where id = v_master;

  perform public._t199_login('a');
  update public.saved_chemicals
     set name = 'T199 Shield 500 SC (renamed)', client_updated_at = now()
   where id = 'd9990000-0000-0000-0000-00000000c001';

  -- …and the applied-spray snapshot is byte-identical.
  select tanks::text into v_tanks_after from public.spray_records
   where id = 'd9990000-0000-0000-0000-00000000e001';
  if v_tanks_before <> v_tanks_after then
    raise exception 'T11 FAILED: historical spray snapshot changed after master/saved updates';
  end if;

  raise notice 'T11 passed (historical spray snapshots immutable)';
end$$;

-- =====================================================================
-- T12  ISOLATION + REFERENCED MASTER CANNOT BE DELETED
-- =====================================================================
do $$
declare
  v_master uuid := current_setting('vinetrack.t199_master', true)::uuid;
  v_n integer;
  v_caught boolean;
begin
  -- An outsider sees no vineyard chemicals (existing RLS intact) even though
  -- the master row itself is shared reference data.
  perform public._t199_login('b');
  select count(*) into v_n from public.saved_chemicals
   where vineyard_id = 'd9990000-0000-0000-0000-000000000001';
  if v_n <> 0 then
    raise exception 'T12 FAILED: outsider can see another vineyard''s chemicals';
  end if;
  select count(*) into v_n from public.master_chemicals where id = v_master;
  if v_n <> 1 then
    raise exception 'T12 FAILED: approved master should be shared reference data';
  end if;

  -- A master row referenced by ANY vineyard cannot be hard-deleted, even by
  -- an admin. Retirement is the only exit.
  perform public._t199_login('adm');
  v_caught := false;
  begin
    delete from public.master_chemicals where id = v_master;
  exception when foreign_key_violation then v_caught := true;
  end;
  if not v_caught then
    raise exception 'T12 FAILED: a referenced master row was hard-deleted';
  end if;

  raise notice 'T12 passed (vineyard isolation intact; referenced master undeletable)';
end$$;

do $$ begin
  raise notice 'sql/199 master chemical catalogue tests: ALL PASSED';
end $$;

rollback;
